admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

admin_homepage:
    path:     /admin
#    defaults: { _controller: AdminBundle:Default:index }


_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin