services:

    app.admin.actualite:
        class: AdminBundle\Controller\ActualiteController
        arguments: [~, AppBundle\Entity\Actualite, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'Actualite', label: Actualite }

    app.admin.admin:
        class: AdminBundle\Controller\UserAdminController
        arguments: [~, AppBundle\Entity\User, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'User', label: User }

    app.admin.eleve:
        class: AdminBundle\Controller\UserEleveController
        arguments: [~, AppBundle\Entity\Eleve, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'User', label: Eleve }

    app.admin.enseignant:
        class: AdminBundle\Controller\UserEnseignantController
        arguments: [~, AppBundle\Entity\Enseignant, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, group: 'User', label: Enseignant }

    app.admin.bibliotheque:
            class: AdminBundle\Controller\BibliothequeController
            arguments: [~, AppBundle\Entity\Bibliotheque, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: 'Bibliotheque', label: Bibliotheque }

    app.admin.livre:
            class: AdminBundle\Controller\LivreController
            arguments: [~, AppBundle\Entity\Livre, ~]
            tags:
                - { name: sonata.admin, manager_type: orm, group: 'Bibliotheque', label: Livre, show_mosaic_button: true }

