<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends EntityRepository
{
    public function findByType($type, $chercher)
    {
        if ($chercher) {
            $result = $this->getEntityManager()
                ->createQuery(
                    'SELECT a
                FROM AppBundle:Article a
                WHERE a.type = :typ AND a.description LIKE :cherche'
                )
                ->setParameter('typ', $type)
                ->setParameter('cherche', '%' . $chercher . '%')
                ->getResult();
        } else {
            $result = $this->getEntityManager()
                ->createQuery(
                    'SELECT a
                FROM AppBundle:Article a
                WHERE a.type = :typ'
                )
                ->setParameter('typ', $type)
                ->getResult();
        }

        return $result;

    }
}
