<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
    public function findByArticle($article)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c
                FROM AppBundle:Commentaire c
                WHERE c.article = :article'
            )
            ->setParameter('article', $article)
            ->getResult();
    }
}
