<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CoursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CoursRepository extends EntityRepository
{
    public function findByNiveau($niveau, $type)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT c, f
                FROM AppBundle:Cours c JOIN c.file f
                WHERE c.niveau = :niveau AND c.type = :type'
            )
            ->setParameter('niveau', $niveau)
            ->setParameter('type', $type)
            ->getResult();
    }
}
